### ISSUE TITLE
Old pages python-guide for creating docker containers?

### ISSUE THREAD

**Issue by avsg8** [docker/python-docker#1]
Just noticed that the old language specific guide for creating a docker container / image has been replaced by this new guide with pre-made python file along with docker-init command for creating a dockerfile. 

Genuinely appreciate the effort on your part to simplify implementing docker for beginners but are the old pages archived somewhere? I found that step by step guide to be more helpful as it actually led us through the steps of creating the files and understanding the functions of each of the commands in the files.

**Comment by craig-osterhout** [comment]
You can find the topics for the older guide at https://github.com/docker/docs/tree/b92ebe5fbfbe4981a7f95797e59431a6d6a96e37/language/python
