### ISSUE TITLE
[EXIT CODE 127] /bin/sh: 1: gunicorn: not found

### ISSUE THREAD

**Issue by benjnicholls** [docker/python-docker#4]
I'm having an issue with the simple app. The command in the dockerfile to run gunicorn doesn't work as gunicorn wasn't installed with requirements.txt. After adding gunicorn (versions 19.9.0 and 21.2.0) to requirements I get an error of empty module name when the import_app function is called in gunicorn's util.py.

![Screenshot (2)](https://github.com/docker/python-docker/assets/121845414/468cce96-69c5-4ac5-b8af-fb58b059c77c)

**Comment by craig-osterhout** [comment]
Thanks for sharing the issue.
When running `docker init`, it will show a gunicorn command as an example.
You should run the app using `python3 -m flask run --host=0.0.0.0`.
You can copy the `docker init` prompt answers from the example in https://docs.docker.com/language/python/develop/#get-the-sample-application
